export const vaccins = [
  {
    id: 0,
    nom: 'BBIBP-CorV',
    inventeurs: ['Sinopharm'],
    lieux_de_production: ['Chine'],
    technologie: 'virus inactivé',
    quantite: 420,
    prix_unitaire: 17,
    approuve: true,
    img: 'bbibp-corv.jpg',
  },

  {
    id: 1,
    nom: 'Sputnik V',
    inventeurs: ['Gamaleya'],
    lieux_de_production: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prix_unitaire: 12,
    approuve: false,
    img: 'sputnik-v.jpg',
  },

  {
    id: 2,
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    lieux_de_production: ['Royaume Unis', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantite: 5028,
    prix_unitaire: 1.78,
    approuve: false,
    img: 'azd1222.jpg',
  },

  {
    id: 3,
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieux_de_production: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantite: 980,
    prix_unitaire: 14,
    approuve: true,
    img: 'tozinameran.jpg',
  },

  {
    id: 4,
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieux_de_production: ['USA'],
    technologie: 'ARN messager',
    quantite: 240,
    prix_unitaire: 28,
    approuve: false,
    img: 'mrna-1273.jpg',
  },

  {
    id: 5,
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieux_de_production: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantite: 110,
    prix_unitaire: 31,
    approuve: false,
    img: 'ad26-cov2-s.jpg',
  },
];
